services:
  - type: web
    name: em-store-backend
    env: python
    buildCommand: "pip install -r em_store/requirements.txt && python em_store/manage.py migrate && python em_store/manage.py collectstatic --noinput"
    startCommand: "gunicorn em_store.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: em_store.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: "*"  # Update this with your domain in production
      # Database settings
      - key: DB_NAME
        fromDatabase:
          name: em-store-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: em-store-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: em-store-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: em-store-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: em-store-db
          property: port

# Database configuration
databases:
  - name: em-store-db
    databaseName: em_store
    user: em_store_user
    plan: free  # or paid plan for production
