# Generated by Django 4.2.7 on 2025-06-20 07:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import unread_emails.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnreadEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the submitter', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the submitter', max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(help_text="User's password (hashed)", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this submission has been processed')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or comments', null=True)),
            ],
            options={
                'verbose_name': 'Unread Email Submission',
                'verbose_name_plural': 'Unread Email Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnreadEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded file', upload_to=unread_emails.models.user_directory_path)),
                ('original_filename', models.CharField(help_text='Original filename of the uploaded file', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unread_email', models.ForeignKey(help_text='The unread email submission this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='unread_emails.unreademail')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['created_at'],
            },
        ),
    ]
