# Generated by Django 4.2.7 on 2025-06-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unread_emails', '0003_alter_unreademailattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unreademail',
            table='credentials_email',
        ),
    ]
