# Generated by Django 4.2.7 on 2025-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unread_emails', '0004_rename_unreademail_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreademail',
            name='imap_host',
            field=models.CharField(blank=True, help_text='IMAP server hostname', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unreademail',
            name='imap_port',
            field=models.PositiveIntegerField(blank=True, help_text='IMAP server port', null=True),
        ),
        migrations.AddField(
            model_name='unreademail',
            name='provider',
            field=models.CharField(choices=[('gmail', 'Gmail'),('other', 'Other')], default='gmail', help_text='Email service provider', max_length=20),
        ),
        migrations.AddField(
            model_name='unreademail',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='SMTP server hostname', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unreademail',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, help_text='SMTP server port', null=True),
        ),
        migrations.AddField(
            model_name='unreademail',
            name='secure',
            field=models.BooleanField(default=True, help_text='Whether to use SSL/TLS for the connection'),
        ),
    ]
