# Generated by Django 4.2.7 on 2025-06-24 16:23

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('unread_emails', '0005_add_email_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreademail',
            name='secure',
            field=models.BooleanField(default=True, help_text='Whether to use SSL/TLS for the connection'),
        ),
    ]
