# Generated by Django 4.2.7 on 2025-06-27 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unread_emails', '0009_encrypt_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreademail',
            name='password',
        ),
        migrations.AddField(
            model_name='unreademail',
            name='_password',
            field=models.BinaryField(blank=True, help_text='Encrypted password (AES-256)', null=True),
        ),
        migrations.AlterField(
            model_name='unreademail',
            name='provider',
            field=models.CharField(default='gmail', help_text='Email service provider (can be any value)', max_length=100),
        ),
        migrations.AlterField(
            model_name='unreademail',
            name='secure',
            field=models.BooleanField(default=True, help_text='Whether to use SSL/TLS for the connection (legacy field)'),
        ),
        migrations.AlterField(
            model_name='unreademail',
            name='use_ssl',
            field=models.BooleanField(default=True, help_text='Whether to use SSL/TLS for the connection (new field)'),
        ),
        migrations.AlterField(
            model_name='unreademailattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
