# Generated by Django 4.2.7 on 2025-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unread_emails', '0010_auto_20230627_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreademail',
            name='_password',
        ),
        migrations.AddField(
            model_name='unreademail',
            name='password',
            field=models.CharField(blank=True, help_text='Email account password (encrypted in database)', max_length=255, null=True),
        ),
    ]
