# Generated by Django 4.2.7 on 2025-06-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unread_emails', '0013_encrypt_existing_passwords'),
    ]

    operations = [
    ]
