# Generated by Django 4.2.7 on 2025-07-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unread_emails', '0002_fix_initial_migration'),
    ]

    operations = [
    ]
