# Generated by Django 4.2.7 on 2025-07-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unread_emails', '0003_add_file_data_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreademailattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='unreademailattachment',
            name='file_data',
            field=models.BinaryField(blank=True, default=b'', help_text='The actual file data', null=True),
        ),
        migrations.AlterField(
            model_name='unreademailattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='Size of the file in bytes'),
        ),
    ]
