# Generated by Django 4.2.7 on 2025-07-10 06:26

from django.db import migrations, models
import unread_emails.models


class Migration(migrations.Migration):

    dependencies = [
        ('unread_emails', '0004_add_download_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unreademailattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Unread Email Attachment', 'verbose_name_plural': 'Unread Email Attachments'},
        ),
        migrations.RemoveField(
            model_name='unreademailattachment',
            name='file_data',
        ),
        migrations.AddField(
            model_name='unreademailattachment',
            name='file',
            field=models.FileField(blank=True, help_text='The actual file', null=True, upload_to=unread_emails.models.UnreadEmailAttachment.unread_email_attachment_path),
        ),
        migrations.AlterModelTable(
            name='unreademailattachment',
            table=None,
        ),
    ]
