# Generated by Django 4.2.7 on 2025-06-19 12:28

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the subscriber', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the subscriber', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('date_of_signup', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the user signed up')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this email is currently active')),
                ('source', models.CharField(default='web_form', help_text='Source of the email entry (web_form, csv_upload, etc.)', max_length=50)),
            ],
            options={
                'verbose_name': 'Email Entry',
                'verbose_name_plural': 'Email Entries',
                'ordering': ['-date_of_signup'],
            },
        ),
    ]
