# Generated by Django 4.2.7 on 2025-06-20 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailentry',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='emailentry',
            name='source',
        ),
        migrations.AddField(
            model_name='emailentry',
            name='day_five',
            field=models.TextField(blank=True, help_text='Day five email status', null=True),
        ),
        migrations.AddField(
            model_name='emailentry',
            name='day_four',
            field=models.TextField(blank=True, help_text='Day four email status', null=True),
        ),
        migrations.AddField(
            model_name='emailentry',
            name='day_nine',
            field=models.TextField(blank=True, help_text='Day nine email status', null=True),
        ),
        migrations.AddField(
            model_name='emailentry',
            name='day_one',
            field=models.TextField(blank=True, help_text='Day one email status', null=True),
        ),
        migrations.AddField(
            model_name='emailentry',
            name='day_seven',
            field=models.TextField(blank=True, help_text='Day seven email status', null=True),
        ),
        migrations.AddField(
            model_name='emailentry',
            name='day_two',
            field=models.TextField(blank=True, help_text='Day two email status', null=True),
        ),
        migrations.AlterField(
            model_name='emailentry',
            name='date_of_signup',
            field=models.DateField(auto_now_add=True, help_text='Date when the user signed up'),
        ),
        migrations.AlterField(
            model_name='emailentry',
            name='email',
            field=models.TextField(help_text='Email address of the subscriber', unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='emailentry',
            name='name',
            field=models.TextField(help_text='Full name of the subscriber'),
        ),
        migrations.AlterModelTable(
            name='emailentry',
            table='email_auto',
        ),
    ]
