# Generated by Django 4.2.7 on 2025-06-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_entry', '0003_alter_emailentry_options_alter_emailentry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='unsubscribe',
            field=models.BooleanField(default=False, help_text='Whether the user has unsubscribed from emails'),
        ),
    ]
