# Generated by Django 4.2.7 on 2025-07-03 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_emailcampaign_created_by'),
        ('email_entry', '0004_emailentry_unsubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='The campaign this email entry is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_entries', to='campaigns.emailcampaign'),
        ),
    ]
