# Generated by Django 4.2.7 on 2025-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_entry', '0005_emailentry_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='client_email',
            field=models.EmailField(blank=True, help_text='Email address of the client who added this entry', max_length=255, null=True),
        ),
    ]
