# Generated by Django 4.2.7 on 2025-07-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignemailattachment_download_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignemailattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
