# Generated by Django 4.2.7 on 2025-07-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaignemailattachment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='provider',
            field=models.CharField(default='gmail', help_text='Email service provider (e.g., gmail, yahoo, cpanel, etc.)', max_length=100),
        ),
    ]
