# Generated by Django 4.2.7 on 2025-07-11 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_emailcampaign_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignemailattachment',
            name='client',
            field=models.ForeignKey(blank=True, default=None, help_text='The client (campaign) this file belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_attachments', to='campaigns.emailcampaign'),
        ),
    ]
